[package]
name = "gitbounties_backend"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Daniel Liu <mr.picklepinosaur@gmail.com>"]
description = ""
repository = ""

[features]

[dependencies]
axum = { version = "0.6", features = ["query"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
serde_json = { version = "1.0" }

dotenv = { version = "0.15" }

env_logger = { version = "0.9" }
log = { version = "0.4" }
