[package]
name = "gitbounties_backend"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Daniel Liu <mr.picklepinosaur@gmail.com>"]
description = ""
repository = ""
build = "build.rs"

[features]

[dependencies]
axum = { version = "0.6", features = ["query"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
surrealdb = { version = "1.0.0-beta.9" }
reqwest = { version = "0.11", features = ["json"] }
ethers = { version = "2.0", features = ["ethers-solc"] }

dotenvy = { version = "0.15" }

anyhow = { version = "1" }
env_logger = { version = "0.9" }
log = { version = "0.4" }

[build-dependencies]
ethers = { version = "2.0", features = ["ethers-solc"] }
serde_json = { version = "1.0" }
