# Download binary for backend and run it

FROM debian:bookworm

EXPOSE 3001

RUN apt-get -y update; apt-get -y install libssl3

COPY target/debug/gitbounties_backend .

RUN chmod 755 ./gitbounties_backend

CMD ["./gitbounties_backend", "--no-https"]
