name: Build
on:
  workflow_dispatch: {}

env:
  binary: gitbounties_backend

jobs:
  release_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: little-core-labs/get-git-tag@v3.0.1
        id: get_version
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - name: download solc
        run: |
          apt-get install solc
      - name: Build
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          release_name: nightly build ${{ github.sha }}
          prerelease: true
          body: Development build of the example shell
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-unknown-linux-gnu/release/${{ env.binary }}
          asset_name: ${{ env.binary }}-linux-${{ github.sha }}.zip
          tag: ${{ github.ref }}
          overwrite: true
